[package]
name = "aws-build-lib"
version = "0.9.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"

description = "Build Rust crates for deployment to AWS EC2 or AWS Lambda"
keywords = ["aws", "lambda", "docker", "build", "ec2"]
license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/nicholasbishop/aws-build"

[dependencies]
anyhow = "1.0"
cargo_metadata = "0.11"
chrono = "0.4"
docker-command = "0.7"
fehler = "1.0"
log = { version = "0.4", features = ["std"] }
sha2 = "0.9"
tempfile = "3.1"
zip = "0.5"